### ISSUE TITLE
Nice Droid Toolbox

### ISSUE THREAD

**Issue by OneHalfSavage** [ruthsarian/Droid-Toolbox#1]
I appreciate this. I have recently started using the Arduino IDE UNO and have moved on to the ESP32. Per your YouTube videos, I've purchased a couple of the TTGO T-Display boards and found them fun to work with. I've never done anything with Blue-Tooth or WIFI so this has been a great learning experience. The main reason I've been getting into breadboards, LEDs, OLEDs, sounds, and other fun things is because of my love of Star Wars. I have fun building props and toys and sharing with my grandkids. They like Pops' Star Wars room and are becoming the next generation of Star Wars fans.

Thank you for taking the time to tutor me in how this works. From your latest changes, I see that I was not properly understanding how the BLE Advertising beacon worked. I was too focused on trying to build a "payload[]" array and that wasn't getting me very far (not for a lack of trying, I spent several hours working various combinations). I'm encouraged that I'm starting to understand some of the concepts of both BLE and Arduino and I look forward to continuing my education.

**Comment by OneHalfSavage** [comment]
I'm looking at your code in a bit more detail, trying to figure out how yours is working when my didn't. I'm focusing on this section in particular:
void set_payload_location_beacon(uint8_t location) {
  load_payload_location_beacon_data();
  payload[4] = (location % 7) + 1;
  pAdvertisementData->setManufacturerData(std::string(reinterpret_cast<char*>(payload), PAYLOAD_SIZE));
  pAdvertising->setAdvertisementData(*pAdvertisementData);
}

Going back and looking at the v1 you had defined the individual location beacons (I may have added some of my own notes):
uint8_t myBeacons_Batuu_Market[OFF_SET]         = {0x83, 0x01, 0x0A, 0x04, 0x01, 0x02, 0xA6, 0x01};                  // Batuu Market
uint8_t myBeacons_Droid_Oil_Bath[OFF_SET]       = {0x83, 0x01, 0x0a, 0x04, 0x02, 0x02, 0xA6, 0x01};                  // Droid Oil Bath
uint8_t myBeacons_Droid_Depot[OFF_SET]          = {0x83, 0x01, 0x0a, 0x04, 0x05, 0x02, 0xA6, 0x01};                  // Droid Depot
uint8_t myBeacons_Droid_Depot2[OFF_SET]        = {0x83, 0x01, 0x0a, 0x04, 0x03, 0x18, 0xBA, 0x01};                  // Droid Depot2
uint8_t myBeacons_Dok_Ondars [OFF_SET]          = {0x83, 0x01, 0x0a, 0x04, 0x06, 0x02, 0xA6, 0x01};                  // Dok-Ondar's
uint8_t myBeacons_Marketplace[OFF_SET]           = {0x83, 0x01, 0x0a, 0x04, 0x06, 0x18, 0xBA, 0x01};                  // Marketplace
uint8_t myBeacons_Ogas_Outside[OFF_SET]        = {0x83, 0x01, 0x0a, 0x04, 0x05, 0xFF, 0xA6, 0x01};                  // Oga's Outside
uint8_t myBeacons_Ogas_Cantina[OFF_SET]        = {0x83, 0x01, 0x0a, 0x04, 0x07, 0xFF, 0xA6, 0x01};                  // Oga's Cantina

uint8_t myBeacons_Resistance[OFF_SET]           = {0x83, 0x01, 0x0a, 0x04, 0x03, 0x02, 0xA6, 0x01};                  // Resistance
uint8_t myBeacons_Resistance_Transport[OFF_SET] = {0x83, 0x01, 0x0a, 0x04, 0x04, 0x02, 0xA6, 0x01};                  // Resistance Transport

uint8_t myBeacons_First_Order[OFF_SET]          = {0x83, 0x01, 0x0a, 0x04, 0x07, 0x02, 0xA6, 0x01};                  // First Order

You are now setting payload[4] by the location (5th position, 4th because 0 is the first?).

Can you tell me what the (location % 7) +1 is about? Is it saying to use positions 1-7 (with the plus 1 saying to start at 1 instead of 0).

It looks like there are no adjustments to payload[5] so does that mean the time interval is 02 (the minimum delay) for all?

This version of "Droid Toolbox" does what I was hoping. I look forward to sharing it with my 8 year old granddaughter. Last summer she build an R2 droid at Galaxy's Edge (East) and I keep her supplied with batteries. She'll be thrilled to see it respond from a cool little box with a screen on it.

Thank you.

**Comment by ruthsarian** [comment]
array indexes start with 0 so payload[4] would be the 5th position in the array. The value in that position, for a location beacon, corresponds to the location in the park. It also corresponds to the sound group the droid will play from when reacting to that beacon. There are a total of 7 possible locations, values 1 through 7. 

The function set_payload_location_beacon() takes 1 parameter, called 'location', which is the location value to insert into the payload. It's possible, through programming error or some other reason, that a value other than 1 through 7 gets passed (like 8). % is the modulo operator; (location % 7) is taking whatever value is in location, dividing it by 7, and returning the remainder. The possible values of this operation will be 0 through 6. I then add 1 so the only possible values that will get assigned to payload[4] will be 1 through 7. It ensures that the value in payload[4] will always be a viable value rather than something that might not work.

The code doesn't currently touch payload[5], the interval, so it is the minimum reaction interval for droids. I plan to make this adjustable eventually, but for now I'm sticking with the value that is most commonly used within Galaxy's Edge.

**Comment by OneHalfSavage** [comment]
Thank you for the explanation.

**Comment by ruthsarian** [comment]
Closing the issue.
