### ISSUE TITLE
Lilygo ttgo T-display not working after install

### ISSUE THREAD

**Issue by Junglematt** [ruthsarian/Droid-Toolbox#2]
I tried to follow the YouTube video and somewhere, I am missing a step. After compiling and writing is complete, I get a "leaving" line.
I have reset the Ttgo T-display board back to factory and the screen works again. I have the droid toolbox ino on the Arduino IDE and the core and, the TFT _eSPI library.

**Comment by ruthsarian** [comment]
The "leaving" line is in the Arduino IDE output window? Is it this:

```
Leaving...
Hard resetting via RTS pin...
```

If so, that's normal. That means the program has been uploaded to your TTGO. If you're receiving a different message, please copy and paste it here so that I can see the full message.

The most common reason for a blank screen is that the wrong LCD screen has been selected when configuring the TFT_eSPI library. Did you modify the file user_setup_select.h that is part of the TFT_eSPI library? If so, which include line did you uncomment? And did you remember to comment out User_Setup.h? This step is covered starting at 15:30 in the video (https://www.youtube.com/watch?v=wEwg2-N3HqM).
