### ISSUE TITLE
Compatibility with Boards/Libraries

### ISSUE THREAD

**Issue by krebeck** [ruthsarian/Droid-Toolbox#4]
When jumping from the .68 to the .70 version of Toolbox, my Arduino IDE wanted to update the Esp32 Board and the TFT_espi libraries to the latest version.  At least one of these resulted in an unsuccessful flash upgrade.  I had to restore the T-Display to factory and back the Board and Library versions back down to known good versions.  After that I had a successful upgrade.  But you might want to add this in a note.

Sorry I couldn't troubleshoot more closely and was changing multiple things about the environment at once but I can definitely say that the most recent versions of the esp32 board version (2.0.15) and TFT_eSPI (2.5.43) did not work and the esp32 2.0.6 and TFT_eSPI 2.5.0 versions definitely did work.

**Comment by ruthsarian** [comment]
The Arduino IDE will check for new versions of all libraries and cores every time it opens and it will ask whether or not you want to install them. This does not indicate that a new version of the code requires a new version of the library, only that a new version of the library is available and, if you choose to allow it, Arduino IDE will download and install it for you. It is OKAY to skip installing these upgrades.

If you install a new version of the TFT_eSPI library then you must perform the edits to user_setup_select.h, user_setup.h, and Setup206_LilyGo_T_Display_S3.h in order for the library to work again. This is because when a new version of the library is installed it overwrites everything in the TFT_eSPI library including any changes you've made to files within the library.

Did you make these changes after upgrading to TFT_eSPI 2.5.43?

**Comment by krebeck** [comment]
Yes I did remember to add the configs to the TFT_eSPI files.  I suspect it might have been the board update, but like I said, I changed two things at the same time - violating the cardinal rule of troubleshooting.  I am running the older T display, not the S3 version.  All that being said, this is purely informational.  Droid Toolbox is so fantastic and it has given me and my son hours of additional fun with our droids.  Happy to do more thorough testing and help in any way I can.

**Comment by ruthsarian** [comment]
I will try updating my environment this evening and loading droid toolbox onto a T-Display.

What version of Arduino IDE do you have? And what OS? Just in case the IDE itself has something to do with this, I want to try and replicate it as best I can.

Thanks

**Comment by krebeck** [comment]
Arduino IDE 2.3.2 running on Windows 10. Like I said, rolling back to the board and library versions shown in your 40 minute full install video (but staying on IDE 2.3.2) worked fine.  Entirely possible that some of the incremental versions between your video and the most recent upgrades would also work fine.

**Comment by ruthsarian** [comment]
My initial tests show it's an issue with the esp32 2.0.15 release. I've got the latest Arduino IDE (2.3.2), the latest TFT_eSPI library installed (2.5.43) and I tested the esp32 boards package from version 2.0.6 up to 2.0.15 and it breaks on 2.0.15, but 2.0.14 and below are fine.

Not sure how deep I'm going to go into investigating this. The github project for the arduino esp32 boards package seems to show a few others having issues with 2.0.15. Maybe it'll get fixed with their next release? I think for now, sticking to 2.0.14 is the way to go.
